# Debug mode
debug: 0 # True/False

# AR.Drone settings
ardrone:
  ip1: 192.168.1.10
  ip2: 192.168.1.11
  speed: 0.1 # 0 to 1

# target1 color and whitebalance from static photo
target1:
  color: [100,168,162] #[117,164,147]
  whiteBalance: 141 #76
  
# OpenCV settings
opencv:
  threshold: 10 # +/- for target color
  lowThresh: 0
  highThresh: 100
  nIters: 10
  minArea: 1000
  width: 640
  height: 360
  saveFiles: 1 # True/False
  
# B, G, R
GREEN: [0,255,0]
BLUE: [255,0,0]
RED: [0,0,255]
WHITE: [255,255,255]
YELLOW: [0,255,255]