# Debug mode
debug: 0 # True/False

# AR.Drone settings
ardrone:
  ip1: 192.168.1.10
  ip2: 192.168.1.11
  turnSpeed: 0.1 # 0 to 1
  moveSpeed: 0.1 # 0 to 1

# target1 color and whitebalance from static photo
target0:
  color: [102,163,170] #[103,128,134]
  whiteBalance: 69 #80.6
  dissize: 215

# target2 color and whitebalance from static photo
target1:
  color: [94,181,185] #[103,128,134]
  whiteBalance: 126 #80.6
  dissize: 100
  
# OpenCV settings
opencv:
  threshold: 35 # +/- for target color
  lowThresh: 0
  highThresh: 1
  nIters: 4
  minArea: 2000
  width: 640
  height: 360
  saveFiles: 0 # True/False
  
# B, G, R
GREEN: [0,255,0]
BLUE: [255,0,0]
RED: [0,0,255]
WHITE: [255,255,255]
YELLOW: [0,255,255]