# Debug mode
debug: 0 # True/False

# AR.Drone settings
ardrone:
  ip1: 192.168.1.10
  speed: 0.05 # 0 to 1
  color: [235,20,20]
  
# Camera
camera:
  ip: 192.168.1.20
  port: 80
  username: root
  password: CSC
  resolution: 640x480
  compression: 30
  fps: 10

# target1 color from static photo
target1:
  color: [135,210,230]
  
# OpenCV settings
opencv:
  threshold: 20 # +/- for target color
  lowThresh: 0
  highThresh: 100
  nIters: 1
  minArea: 100
  width: 480
  height: 640
  saveFiles: 1 # True/False
  
# B, G, R
GREEN: [0,255,0]
BLUE: [255,0,0]
RED: [0,0,255]
WHITE: [255,255,255]
YELLOW: [0,255,255]