# Debug mode
debug: 0 # True/False

# AR.Drone settings
ardrone:
  ip1: 192.168.1.10
  ip2: 192.168.1.11

# target1 color and whitebalance from static photo
target1:
  color: [133,87,61]
  whiteBalance: 122.87
  
# OpenCV settings
opencv:
  threshold: 10 # +/- for target color
  lowThresh: 0
  highThresh: 100
  nIters: 2
  minArea: 100
  saveFiles: 0 # True/False
  width: 640
  height: 360
  
# B, G, R
GREEN: [0,255,0]
BLUE: [255,0,0]
RED: [0,0,255]
WHITE: [255,255,255]
YELLOW: [0,255,255]