# Debug mode
debug: 0 # True/False

# AR.Drone settings
ardrone:
  ip1: 192.168.1.10
  ip2: 192.168.1.11
  turnSpeed: 0.25 # 0 to 1
  moveSpeed: 0.1 # 0 to 1

# target0 color and whitebalance from static photo (lightsaber theater)
target0:
  color: [250,250,63]
  whiteBalance: 71
  threshold: 50 # +/- for target color
  dissize: 150

# target1 color and whitebalance from static photo (lightsaber upstairs)
target1:
  color: [247,255,150]
  whiteBalance: 140
  threshold: 25 # +/- for target color
  dissize: 100


# OpenCV settings
opencv:
  lowThresh: 0
  highThresh: 1
  nIters: 10
  minArea: 1000
  width: 640
  height: 360
  saveFiles: 0 # True/False
  
# B, G, R
GREEN: [0,255,0]
BLUE: [255,0,0]
RED: [0,0,255]
WHITE: [255,255,255]
YELLOW: [0,255,255]